autos_dj4e/urls.py
from django.urls import path

from . import views

app_name = 'autos_dj4e'
urlpatterns=[
    path('',views.indexView.as_view(),name='index'),
    path('auto/create/',views.auto_create.as_view(),name="auto_create"),
    path('auto/<int:pk>/edit/',views.auto_edit.as_view(),name='auto_edit'),
    path('auto/<int:pk>/delete/',views.auto_delete.as_view(),name="auto_delete"),
    path('make/',views.view_all_makes.as_view(),name='make_view'),
    path('make/create/',views.make_Create.as_view(),name='make_create'),
    path('make/<int:make_id>/update',
        views.make_update.as_view(),
        name='make_update'
    ),
    path('make/<int:make_id>/delete/',
        views.make_delete.as_view(),
        name="make_delete"
    ),

]

home/urls.py
from django.urls import path

from . import views

app_name='home'

urlpatterns = [
    path('',views.index,name='index'),
]

testSite/urls.py
import os
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import url  #depricated(alias used: re_path())
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print('\n',BASE_DIR)
SITE_ROOT = os.path.join(BASE_DIR,'site')
CSS_ROOT = os.path.join(BASE_DIR,'css')
urlpatterns = [
    path('',include('home.urls',namespace='home')),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    re_path(r'^site/(?P<path>.*)$',serve,
        {'document_root' : SITE_ROOT,'show_indexes': True},
        name='site_path'
    ),
    re_path(r'^css/(?P<path>.*)$',serve,
        {'document_root':CSS_ROOT,'show_indexes':True},
        name='css_test'
    ),
    path('samples/',include('samples.urls',namespace='samples')),
    path('music/',include('MusicLib.urls',namespace='music')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('authz/',include('authz_dj4e.urls')),
    path('autos/',include('autos_dj4e.urls',namespace='autos')),
    path('crispy/',include('crispy_dj4e.urls',namespace='crispy')),
    # path('unesco/',include('unesco.urls',namespace='unesco')),
    path('bootstrap/',include('bootstrap_learn.urls',namespace='bs4')),
    path('myarts/',include('myArticles.urls',namespace="articles")),
    path('pics/',include('pics_dj4e.urls',namespace='pics')),
    path('forum/',include('forum_dj4e.urls',namespace='forum')),
    path('chat/',include('chat_dj4e.urls',namespace='chat')),
    path('fav/',include('favourite.urls',namespace='fav')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autos_dj4e/models.py
from django.db import models
from django.core.validators import MinLengthValidator
# Create your models here.

class Make(models.Model):
    name = models.CharField(
            verbose_name='Name(Auto):',
            max_length=200,
            help_text='(eg.Honda)',
            validators=[MinLengthValidator(2,'minimum 2 characters required.')]
    )

    def __str__(self):
        return self.name

class Auto(models.Model):
    name = models.CharField(
            max_length=200,
            validators= [MinLengthValidator(5,'minimum 5 characters required.')],
            verbose_name='Name(Auto)'
    )
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    make = models.ForeignKey(
            'Make',
            on_delete=models.CASCADE,
            null=False
    )

    def __str__(self):
        return self.name

autos_dj4e/forms.py
from django.forms import ModelForm
from autos_dj4e.models import Make

# class makeForm(ModelForm):
#     class Meta:
#         model = Make
#         fields = '__all__'
class MakeForm(ModelForm):
    class Meta:
        model = Make
        fields = '__all__'

autos_dj4e/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import ListView,View
# https://docs.djangoproject.com/en/3.1/ref/class-based-views/generic-editing/
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponse
from autos_dj4e.forms import MakeForm
from .models import Auto,Make
# Create your views here.

class indexView(LoginRequiredMixin,ListView):
    model=Auto
    template_name='autos_dj4e/index.html'
    context_object_name='auto_list'

    # Add additional context
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['make_count']= Make.objects.all().count()
        return context



class view_all_makes(LoginRequiredMixin,ListView):
    model=Make
    template_name='autos_dj4e/make_view.html'
    context_object_name='make_list'



class make_Create(LoginRequiredMixin,View):
    template="autos_dj4e/make_create_form.html"
    success_url=reverse_lazy('autos_dj4e:index')
    def get(self, request):
        form = MakeForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)
    
    def post(self,request):
        form = MakeForm(request.POST)
        if not form.is_valid() :
            ctx={
                'form' : form
            }
            return render(request,self.template,ctx)
        form.save()
        return redirect(self.success_url)
        


class make_update(LoginRequiredMixin,View):
    template='autos_dj4e/make_update.html'
    success_url = reverse_lazy('autos_dj4e:make_view')

    def get(self,request,make_id):
        make_data=get_object_or_404(Make,pk=make_id)
        form = MakeForm(instance=make_data)
        ctx={'form':form}
        return render(request,self.template,ctx)

    def post(self,request,make_id):
        check_existence_make=get_object_or_404(Make,pk=make_id)
        form = MakeForm(request.POST,instance=check_existence_make)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            ctx={'form':form}
            return render(request,self.template,ctx)

        
        
class make_delete(LoginRequiredMixin,View):
    # template name can be any unless we use generic edit views(CreatView,DeleteView etc..)              
    template='autos_dj4e/make_confirm_delete.html'
    success_url=reverse_lazy('autos_dj4e:make_view')
    model=Make
    def get(self,request,make_id):
        # check whether the entry  exist in db otherwise raise http404
        check_existence_make = get_object_or_404(self.model,pk=make_id)
        # context passed to delete confirm page
        ctx ={'make_to_delete':check_existence_make}
        return render(request,self.template,ctx)
    
    def post(self,request,make_id):
        # check whether the entry  exist in db otherwise raise http404
        check_make = get_object_or_404(self.model,pk=make_id)
        # deleting the entry whose pk=make_id
        check_make.delete() 
        # redirect to a success_url
        return redirect(self.success_url)

# generic edit view: CreateView 
class auto_create(LoginRequiredMixin,CreateView):
    model=Auto
    fields=['name','make','mileage','comments']
    success_url=reverse_lazy('autos_dj4e:index')
    op='Create'
    # default name is '[modelName]_form'.Here 'auto_form'
    # if we need to explicitly specify teemplate use 'template_name attribute
    # eg: template_name='autos_dj4e/auto_form_test.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['operation']= self.op
        context['submit_val']=self.op
        return context

# generic edit view : UpdateView
class auto_edit(LoginRequiredMixin,UpdateView):
    model=Auto
    fields="__all__"
    success_url=reverse_lazy('autos_dj4e:index')
    op='Edit'

    # additional context
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['operation']= self.op
        context['submit_val']='Update'
        return context

class auto_delete(LoginRequiredMixin,DeleteView):
    model=Auto
    success_url=reverse_lazy('autos_dj4e:index')

autos_dj4e/templates/autos_dj4e/auto_confirm_delete.html
{% extends "autos_dj4e/base.html" %}

{% block title %}
    delete auto
{% endblock title %}

{% block content %}
    
    <form action="" method="post">
        {% csrf_token %}
        <p>Do you want to delete <strong>{{auto.name}}</stong>
        <br>
        <input type="submit" value="Yes,Confirm">
        <input type="submit"
            onclick="window.location='{% url 'autos_dj4e:index' %}';return false"
            value="Cancel"
        >
    </form>
{% endblock content %}  

autos_dj4e/templates/autos_dj4e/auto_form.html
{% extends "autos_dj4e/base.html" %}
{% block title %}
    create autos_dj4e/base.html
{% endblock title %}

{% block content %}
    <h1>{{operation}}Auto</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% comment %}
            Displays the derived form the model 'Auto' 
        {% endcomment %}
        {{form.as_p}}
        <input type="submit" value="{{submit_val}}">
        <input type="submit"
            onclick="window.location='{% url 'autos_dj4e:index'%}';return false;"
            value="Cancel"
        >
    </form>
{% endblock content %}

autos_dj4e/templates/autos_dj4e/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

autos_dj4e/templates/autos_dj4e/index.html
{% extends "autos_dj4e/base.html" %}
{% block title %}
    index
{% endblock %}

{% block content %}

<h1>Auto List</h1>

{% if auto_list %}
    <ul>
    {% for auto in auto_list %}
        <li>{{auto.name}}
            ({{auto.make}})
            &nbsp
            (<a href = "{% url 'autos_dj4e:auto_edit' auto.id %}">Edit</a> | <a href="{% url 'autos_dj4e:auto_delete' auto.id %}">Delete</a>) 
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Auto list is empty</p>
{% endif %}

<p>
{% if make_count > 0 %}
    <a href="{% url 'autos_dj4e:auto_create' %}">Add an auto</a>
{% else %}
    Please add a make before you add an auto.
{% endif %}
</p>
<p>
{% if make_count > 0%}
</p>
{% endif %}
{% if make_count > 0 %}
    <a href="{% url 'autos_dj4e:make_view' %}">View makes</a>({{make_count}})
    &nbsp |
    <a href="{% url 'autos_dj4e:make_create' %}">Add a make</a>
{% endif %}
<br><br>
<a href="{% url 'logout'%}?next={{request.path}}">Logout</a>
{% endblock %}

autos_dj4e/templates/autos_dj4e/make_confirm_delete.html
{% extends "autos_dj4e/base.html" %}

{% block title %}
    confirm delete
{% endblock title %} 

{% block content %}
<form action="" method="post">
{% csrf_token %}
<p>Do you want to delete make 
    <strong>"{{make_to_delete.name}}"</strong>
</p>
<input type="Submit" value="Delete">
<input type="submit"
    onclick="window.location='{% url 'autos_dj4e:make_view' %}';return false;"
    value="Cancel">
</form>
{% endblock content %}   

autos_dj4e/templates/autos_dj4e/make_create_form.html
{% extends 'autos_dj4e/base.html' %}
{% block title%}
    create
{% endblock %}

{% block content %}
<h1>Create Make</h1>
<form action="" method="post">
{% csrf_token %}
<table> 
{{form.as_table}}
</table>
<input type="submit" value="Submit">
<input type="submit" 
    onclick="window.location='{% url 'autos_dj4e:index' %}'; return false;"
    value="Cancel"
>
</form>
{% endblock %}

autos_dj4e/templates/autos_dj4e/make_update.html
{% extends "autos_dj4e/base.html" %}
{% block title %}
 update make
{% endblock title %}
{% block content %}
    <h1>Make</h1>
    <form action="" method="post">
    {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update">
        <input type="submit" 
            onclick="window.location='{% url 'autos_dj4e:make_view' %}'; return false;"
            value="Cancel"
        >
    </form>
{% endblock content %}

autos_dj4e/templates/autos_dj4e/make_view.html
{% extends "autos_dj4e/base.html" %}
{% block title %}
    makes
{% endblock title %}

{% block content %}
<h1>Make List</h1>
{% if make_list %}
    <ul>
    {% for make in make_list %}
        <li>{{make.name}}({{make.id}})
            &nbsp
            (<a href="{% url 'autos_dj4e:make_update' make.id %}">Edit</a> 
            | <a href="{% url 'autos_dj4e:make_delete' make.id %}">Delete</a>)
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p> Make  List is emmpty.</p>
    <p>You can <a href="">add make</a></p>
{% endif %}
<a href="{% url 'autos_dj4e:index' %}"> Go back</a>
{% endblock %} 