forum_dj4e/urls.py
from django.urls import path
from django.urls import reverse_lazy

from . import views

app_name='forum_dj4e'

urlpatterns = [
    path('',views.ForumIndexView.as_view(),name='forum_index'),
    path('create/',views.CreateForumView.as_view(success_url=reverse_lazy('forum:forum_index')),name='forum_create'),
    path('update/<int:pk>/',views.UpdateForumView.as_view(success_url=reverse_lazy('forum:forum_index')),name='forum_update'),
    path('delete/<int:pk>/',views.DeleteForumView.as_view(success_url=reverse_lazy('forum:forum_index')),name='forum_delete'),
    path('detail/<int:pk>/',views.DetailForumView.as_view(),name='forum_detail'),
    path('comment-create/<int:pk>/',views.CommentCreate.as_view(),name='comment_create'),
    path('comment/delete/<int:pk>/',views.CommentDeleteView.as_view(),name='comment_delete'),
]

home/urls.py
from django.urls import path

from . import views

app_name='home'

urlpatterns = [
    path('',views.index,name='index'),
]

testSite/urls.py
import os
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import url  #depricated(alias used: re_path())
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print('\n',BASE_DIR)
SITE_ROOT = os.path.join(BASE_DIR,'site')
CSS_ROOT = os.path.join(BASE_DIR,'css')
urlpatterns = [
    path('',include('home.urls',namespace='home')),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    re_path(r'^site/(?P<path>.*)$',serve,
        {'document_root' : SITE_ROOT,'show_indexes': True},
        name='site_path'
    ),
    re_path(r'^css/(?P<path>.*)$',serve,
        {'document_root':CSS_ROOT,'show_indexes':True},
        name='css_test'
    ),
    path('samples/',include('samples.urls',namespace='samples')),
    path('music/',include('MusicLib.urls',namespace='music')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('authz/',include('authz_dj4e.urls')),
    path('autos/',include('autos_dj4e.urls',namespace='autos')),
    path('crispy/',include('crispy_dj4e.urls',namespace='crispy')),
    # path('unesco/',include('unesco.urls',namespace='unesco')),
    path('bootstrap/',include('bootstrap_learn.urls',namespace='bs4')),
    path('myarts/',include('myArticles.urls',namespace="articles")),
    path('pics/',include('pics_dj4e.urls',namespace='pics')),
    path('forum/',include('forum_dj4e.urls',namespace='forum')),
    path('chat/',include('chat_dj4e.urls',namespace='chat')),
    path('fav/',include('favourite.urls',namespace='fav')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum_dj4e/models.py
from django.db import models
from django.core.validators import MinLengthValidator

from django.conf import settings
# Create your models here.


class Forum(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(5,'Title must be greater than 5 characters')]
    )
    text = models.TextField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='forum_owner'
        )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    comments = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Comment',
        related_name='forum_comments'
    )
    
    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(5,'comment must be greater than 5 charecters')]
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text
    

    

forum_dj4e/forms.py
from django.forms import ModelForm,CharField
from .models import Comment


class CommentForm(ModelForm):
    text=CharField(max_length=200,label="Comment")
    class Meta:
        model = Comment
        fields = ['text']

forum_dj4e/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from django.http import HttpResponse
from django.contrib.auth.mixins  import LoginRequiredMixin
from django.urls import reverse


from .owner import OwnerListView,OwnerDetailView,OwnerCreateView,OwnerUpdateView,OwnerDeleteView
from .forms import CommentForm
from .models import Forum,Comment
# Create your views here.

class ForumIndexView(OwnerListView):
    model=Forum

class CreateForumView(OwnerCreateView):
    model = Forum
    fields= ['title','text']

class UpdateForumView(OwnerUpdateView):
    model = Forum
    fields= ['title','text']

class DeleteForumView(OwnerDeleteView):
    model=Forum

class DetailForumView(OwnerDetailView):
    model=Forum
    secondary_model=Comment
    def get_context_data(self, **kwargs):
        print('Enter get context')
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CommentForm()
        print('forum key:',self.kwargs['pk']) 
        comments = self.secondary_model.objects.filter(forum=self.kwargs['pk']).order_by('-updated_at')
        # print(comments)
        context['comment_list'] = comments
        # print(context)
        return context

class CommentCreate(LoginRequiredMixin, View):
    def post(self,request,pk):
        f = get_object_or_404(Forum,pk=pk)
        print('Entered comment create view')
        comment = Comment(text=request.POST['text'],owner=request.user,forum = f)
        # print(comment)
        comment.save()
        return redirect(reverse('forum:forum_detail' , args=(pk,)))


class CommentDeleteView(OwnerDeleteView):
    model = Comment

    def get_success_url(self):
        print('Entered get_success_url method')
        # print(self.object)
        forum = self.object.forum
        print('forum:',forum)
        return reverse('forum:forum_detail',args=[forum.id])

forum_dj4e/templates/forum_dj4e/comment_confirm_delete.html
{% extends 'home/base_menu1.html' %}

{% block title %}
    My Forum
{% endblock title %}
{% block logo %}
<i class="fa fa-file-text-o fa-2x" aria-hidden="true"></i> &nbsp&nbsp
{% endblock logo %} 


{% block welcome %}
    <div class="row justify-content-center mt-4 hrr">
        <div class="col-10 col-sm-6  text-center">
            <h1>Delete {{comment.title}}</h1>
            <hr>
        </div>
    </div>   
{% endblock welcome %}

{% block content %}
  
<div class="row justify-content-center">
    <div class="col-auto ">
    <form action="" method="post">
        {% csrf_token %}
    <input type="submit" class="btn btn-primary"  value="Confirm">
    </div>  
    <div class="col-auto">
    <input type="submit" class="btn btn-primary" onclick="window.location='{% url 'forum:forum_detail' comment.forum.id %}';return false;" value="cancel">
</form>
</div>

</div>  
    
{% endblock content %}

forum_dj4e/templates/forum_dj4e/forum_confirm_delete.html
{% extends 'home/base_menu1.html' %}

{% block title %}
    My Forum
{% endblock title %}
{% block logo %}
<i class="fa fa-file-text-o fa-2x" aria-hidden="true"></i> &nbsp&nbsp
{% endblock logo %} 


{% block welcome %}
    <div class="row justify-content-center mt-4 hrr">
        <div class="col-10 col-sm-6  text-center">
            <h1>Delete {{forum.title}}</h1>
            <hr>
        </div>
    </div>   
{% endblock welcome %}

{% block content %}
  
<div class="row justify-content-center">
    <div class="col-auto ">
    <form action="" method="post">
        {% csrf_token %}
    <input type="submit" class="btn btn-primary"  value="Confirm">
    </div>  
    <div class="col-auto">
    <input type="submit" class="btn btn-primary" onclick="window.location='{% url 'forum:forum_index' %}';return false;" value="cancel">
</form>
</div>

</div>  
    
{% endblock content %}

forum_dj4e/templates/forum_dj4e/forum_detail.html
{% extends 'home/base_menu1.html' %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block title %}
    My Forum
{% endblock title %}
{% block logo %}
<i class="fa fa-file-text-o fa-2x" aria-hidden="true"></i> &nbsp&nbsp
{% endblock logo %} 


{% block welcome %}
    <div class="row justify-content-center mt-4 hrr">
        <div class="col-10 col-sm-6  text-center">
            <h1> {{forum.title}}</h1>
            <hr>
        </div>
    </div>   
{% endblock welcome %}

{% block content %}
    <div class="row justify-content-center ">
            <div class="col-12 col-sm-6">
                {{forum.text}}
            </div>
    </div>  
    <div class="row justify-content-center ">
        <div class="col-12 col-sm-6">
            {{forum.created_at|naturaltime }}
        </div>
    </div> 
    <div class="row justify-content-center mt-5">
        <div class="col-12 col-sm-6">

        <form action="{% url 'forum:comment_create' forum.id %}" method="post">
        
            {% csrf_token %}
            {{comment_form | crispy }}
        </div>
    </div> 
    <div class="row justify-content-center mb-4">
        <div class="col-12 col-sm-6 ">
        <input type="submit" class="btn btn-sm border-secondary "  value="Submit">
        <input type="submit" class="btn btn-sm border-secondary " onclick="window.location='{% url 'forum:forum_index' %}'" value="All Forums">
        </div>
        
        </form>

    </div> 
    {% for comment in comment_list  %}
    <div class="row justify-content-center mt-2">
        <div class="col-9 col-sm-4 bg-light  ">
                {{comment.text}}      
        </div>
        
        {% if user == comment.owner %}
             
        <div class="col-3 col-sm-2 p-2 m-2 text-right">
            <a href="{% url 'forum:comment_delete' comment.id %}"><i class="fa fa-trash-o del_ico fa-lg"  aria-hidden="true"></i>
            </i>
            </a>
        </div>
        {% endif %}

    </div>  
    {% endfor %} 
    
{% endblock content %}

forum_dj4e/templates/forum_dj4e/forum_form.html
{% extends 'home/base_menu1.html' %}
{% load crispy_forms_tags %}
{% block title %}
    My Forum
{% endblock title %}
{% block logo %}
<i class="fa fa-file-text-o fa-2x" aria-hidden="true"></i> &nbsp&nbsp
{% endblock logo %} 


{% block welcome %}
    <div class="row justify-content-center mt-4 hrr">
        <div class="col-10 col-sm-6  text-center">
            <h1>Forum</h1>
            <hr>
        </div>
    </div>   
{% endblock welcome %}

{% block content %}
    <form action="" method="POST">
    {% csrf_token %}
    <div class="row justify-content-center ">
            <div class="col-12 col-sm-6">
                {{form|crispy}}
            </div>
    </div>  
    <div class="row justify-content-center">
        <div class="col-auto ">
        <input type="submit" class="btn btn-primary"  value="Submit">
        </div>  
        <div class="col-auto">
        <input type="submit" class="btn btn-primary" onclick="window.location='{% url 'forum:forum_index' %}'" value="cancel">
        </div>
    </div>  
    
{% endblock content %}

forum_dj4e/templates/forum_dj4e/forum_list.html
{% extends 'home/base_menu1.html' %}

{% block title %}
    Forum
{% endblock title %}
{% block logo %}
<i class="fa fa-file-text-o fa-2x" aria-hidden="true"></i> &nbsp&nbsp
{% endblock logo %} 


{% block welcome %}
    <div class="row justify-content-center mt-4 hrr">
        <div class="col-10 col-sm-6  text-center">
            <h1>Forums</h1>
            <hr>
        </div>
    </div>   
{% endblock welcome %}

{% block content %}
    {% for forum in forum_list %}
        <div class="row justify-content-center mt-2">

            <div class="col-10 col-sm-4  bg-light p-2">
                <a href="{% url 'forum:forum_detail' forum.id %}">{{forum.title}}</a> 
                
            </div>
            
            <div class="col-10 col-sm-4  bg-light p-2">
                {% if forum.owner == user %}
                <div class="row float-right">
                    <div class="col p-2 m-2">
                        <a href="{% url 'forum:forum_update' forum.id %}"><i class="fa fa-pencil-square edit_ico fa-lg"  aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="col p-2 m-2">
                        <a href="{% url 'forum:forum_delete' forum.id %}"><i class="fa fa-trash-o del_ico fa-lg"  aria-hidden="true"></i>
                        </i>
                        </a>
                    </div>
                </div>
                {% else %}
                <div class="col-10 col-sm-4  bg-light p-4">
                </div>
                {% endif %}

            </div>
            
            

        </div> 
        
    {% endfor %}

    <div class="row justify-content-center mt-2">
        
        <div class="col-10  mr-2 p-2">
                    <a href="{% url 'forum:forum_create' %}" >
                        <i class="fa fa-plus-square bg-warning " aria-hidden="true"> Add Forum</i>
                    </a>
        </div>
            
    </div>  
    
{% endblock content %}