chat_dj4e/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'chat_dj4e'

urlpatterns = [
    path('',views.IndexView.as_view(),name='chat_index'),
    path('syntax',TemplateView.as_view(template_name='chat_dj4e/syntax.html'),name='syntax'),
    path('json_test',views.json_test,name='json_test'),
    path('chat_window',views.ChatView.as_view(),name = 'chat_view'),
    path('message_list',views.MessageList.as_view(),name='message_list'),
]

home/urls.py
from django.urls import path

from . import views

app_name='home'

urlpatterns = [
    path('',views.index,name='index'),
]

testSite/urls.py
import os
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import url  #depricated(alias used: re_path())
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print('\n',BASE_DIR)
SITE_ROOT = os.path.join(BASE_DIR,'site')
CSS_ROOT = os.path.join(BASE_DIR,'css')
urlpatterns = [
    path('',include('home.urls',namespace='home')),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    re_path(r'^site/(?P<path>.*)$',serve,
        {'document_root' : SITE_ROOT,'show_indexes': True},
        name='site_path'
    ),
    re_path(r'^css/(?P<path>.*)$',serve,
        {'document_root':CSS_ROOT,'show_indexes':True},
        name='css_test'
    ),
    path('samples/',include('samples.urls',namespace='samples')),
    path('music/',include('MusicLib.urls',namespace='music')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('authz/',include('authz_dj4e.urls')),
    path('autos/',include('autos_dj4e.urls',namespace='autos')),
    path('crispy/',include('crispy_dj4e.urls',namespace='crispy')),
    # path('unesco/',include('unesco.urls',namespace='unesco')),
    path('bootstrap/',include('bootstrap_learn.urls',namespace='bs4')),
    path('myarts/',include('myArticles.urls',namespace="articles")),
    path('pics/',include('pics_dj4e.urls',namespace='pics')),
    path('forum/',include('forum_dj4e.urls',namespace='forum')),
    path('chat/',include('chat_dj4e.urls',namespace='chat')),
    path('fav/',include('favourite.urls',namespace='fav')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat_dj4e/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Message(models.Model):
    text = models.TextField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete= models.CASCADE
        )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text
    

chat_dj4e/forms.py
from django import forms
from .models import Message
class ChatForm(forms.ModelForm):
    text = forms.CharField(max_length=200)
    class Meta:
        model = Message
        fields = ['text']
       

chat_dj4e/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy,reverse
from django import forms
from django.views.generic import CreateView
from django.contrib.humanize.templatetags.humanize import naturaltime
import time

from .models import Message
from .forms import ChatForm
# Create your views here.

class IndexView(View):
    def get(self,request):
        return render(request,'chat_dj4e/index.html')

# just print json data
def json_test(request):
    data = {
        'name':'Manoj',
        'age':'25'
    }
    print(data)
    return JsonResponse(data)

# chat window 
# class ChatView(LoginRequiredMixin,CreateView):
#     model = Message
#     template_name='chat_dj4e/chat.html'
#     form_class = ChatForm
#     success_url = reverse_lazy('chat:chat_view')
#     def form_valid(self,form):
#         print('form_valid called')
#         object = form.save(commit=False)
#         object.owner = self.request.user
#         object.save()
#         return super(ChatView,self).form_valid(form)

    
class  ChatView(LoginRequiredMixin, View):
    def get(self,request):
        form = ChatForm()
        ctx={'form' : form}
        return render(request,'chat_dj4e/chat.html',ctx)
    
    def post(self,request):
        print(request)
        message = Message(text=request.POST['text'],owner = request.user)
        message.save()
        return redirect(reverse('chat:chat_view'))

class MessageList(LoginRequiredMixin,View):
    def get(self,request):
        messages = Message.objects.all().order_by('-created_at')[:10]
        print(messages)
        result = []
        for msg in messages:
            res = [msg.text,naturaltime(msg.created_at)]
            result.append(res)
        return JsonResponse(result,safe=False) 

chat_dj4e/templates/chat_dj4e/chat.html
{% extends 'home/base_menu.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Submit">
        <input type="reset" value="Clear">
        <a href="{% url 'chat:chat_index' %}" class="btn">Cancel</a>
    </form>
    <br>
    <div class="row center-block">
        <div class="col-6 col-sm-6">
            <p id='chat_content'>
                <img src="{% static 'chat_dj4e/spinner.gif' %}" alt="Loading symbol"> 
            </p>
        </div>
    </div>

    <script type="text/javascript">
        // function for requesting json, called repeatedly in ech 4 seconds
        function UpdateMessage(){
            console.log('Requesting Json');
            $.getJSON('{% url 'chat:message_list' %}', function(msg_list){
                console.log('Json',msg_list);
                $('#chat_content').empty();
                for (var i = 0; i < msg_list.length; i++ ) {
                    msg  = msg_list[i];
                    $('#chat_content').append('<p>' + msg[0] + '<br>&nbsp&nbsp' + msg[1] + '</p>\n');
                }
                setTimeout('UpdateMessage()', 4000);
            });
        }

        // calling updateMessage() & make json requests are not cached

        $(document).ready( function(){
            $.ajaxSetup({cache : false});
            setTimeout('UpdateMessage()', 2000);
        });
    </script>
{% endblock content %}

chat_dj4e/templates/chat_dj4e/index.html
{% extends 'home/base_menu.html' %}


{% block content %}
    <a href="{% url 'chat:syntax' %}" class="btn btn-primary p3 ">Syntax</a>|
    <a href="{% url 'chat:message_list' %}" class="btn btn-primary p3 ">Json dump</a> |
    <a href="{% url 'chat:chat_view' %}" class="btn btn-primary p3 ">Chat</a>
    <br><br>
    <div id="json_data">
        This text will replace in two seconds
    </div>

    <script type="text/javascript">
        $(document).ready(function(){
            $.getJSON('{% url 'chat:json_test' %}', function(data){
                console.log(data);
                $("#json_data").html('name: '+data.name+'<br> Age:'+data.age)  ;           
            })
        });

    </script>
{% endblock content %}

chat_dj4e/templates/chat_dj4e/syntax.html
{% extends 'home/base_menu.html' %}


{% block content %}
<script type="text/javascript">
    who = {
        "name": "Chuck",
        "age": 29, 
        "college": true,
        "offices" : [ "3350DMC", "3437NQ" ],
        "skills" : { "fortran": 10, "C": 10, 
            "C++": 5, "python" : 7 }
    };
    console.log('Test')
    console.log(who);
</script>
    <p>Check out the console.log to see the cool object</p>
    <pre>
    who = {
        "name": "Chuck",
        "age": 29, 
        "college": true,
        "offices" : [ "3350DMC", "3437NQ" ],
        "skills" : { "fortran": 10, "C": 10, 
            "C++": 5, "python" : 7 }
    };
    </pre>
    <a href="{% url 'chat:chat_index' %}" class="btn btn-primary p3 ">Back</a>

{% endblock content %}