favourite/urls.py
from django.urls import path

from . import views

app_name = 'favourites'

urlpatterns = [
    path('',views.ThingListView.as_view(),name='index'),
    path('create',views.ThingCreateView.as_view(),name='thing_create'),
    path('update/<int:pk>',views.ThingUpdateView.as_view(),name='thing_update'),
    path('delete/<int:pk>',views.ThingDeleteView.as_view(),name='thing_delete'),
    path('add-to-favourite/<int:pk>',views.AddFavourite.as_view(),name="add_favourite"),
    path('unfavourite/<int:pk>',views.UnFavourite.as_view(),name='unfavourite')
]

home/urls.py
from django.urls import path

from . import views

app_name='home'

urlpatterns = [
    path('',views.index,name='index'),
]

testSite/urls.py
import os
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import url  #depricated(alias used: re_path())
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print('\n',BASE_DIR)
SITE_ROOT = os.path.join(BASE_DIR,'site')
CSS_ROOT = os.path.join(BASE_DIR,'css')
urlpatterns = [
    path('',include('home.urls',namespace='home')),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    re_path(r'^site/(?P<path>.*)$',serve,
        {'document_root' : SITE_ROOT,'show_indexes': True},
        name='site_path'
    ),
    re_path(r'^css/(?P<path>.*)$',serve,
        {'document_root':CSS_ROOT,'show_indexes':True},
        name='css_test'
    ),
    path('samples/',include('samples.urls',namespace='samples')),
    path('music/',include('MusicLib.urls',namespace='music')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('authz/',include('authz_dj4e.urls')),
    path('autos/',include('autos_dj4e.urls',namespace='autos')),
    path('crispy/',include('crispy_dj4e.urls',namespace='crispy')),
    # path('unesco/',include('unesco.urls',namespace='unesco')),
    path('bootstrap/',include('bootstrap_learn.urls',namespace='bs4')),
    path('myarts/',include('myArticles.urls',namespace="articles")),
    path('pics/',include('pics_dj4e.urls',namespace='pics')),
    path('forum/',include('forum_dj4e.urls',namespace='forum')),
    path('chat/',include('chat_dj4e.urls',namespace='chat')),
    path('fav/',include('favourite.urls',namespace='fav')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

favourite/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings



# Create your models here.


class Thing(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2,"Title must be greater than two characters.")]
    )
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    favourite = models.ManyToManyField(
        settings.AUTH_USER_MODEL , through='Fav',related_name='favourite_things'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Fav(models.Model):
    thing = models.ForeignKey(Thing,on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='favs_user')
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['thing','user'],name='unique_favourite')
        ]
    def __str__(self):
        return '{0} likes {1}'.format(self.user.username,self.thing.title[:10])
    

favourite/views.py
from django.shortcuts import render,get_object_or_404
from django.views import View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.db.utils import IntegrityError

from .models import Thing,Fav
from forum_dj4e.owner import OwnerCreateView,OwnerDeleteView,OwnerListView,OwnerUpdateView
class ThingListView(OwnerListView):
    model = Thing
    template_name = 'favourite/index.html'

    def get(self,request):
        print('Executing ThingListView get()')
        fav_list=None
        thing_list = Thing.objects.all()
        # print(thing_list)
        usr = request.user
        # print(dir(usr))
        # print(fvrt_list)
        if usr.is_authenticated:
            print('user is authenticated')
            try:
                print('Entered try block')
                fav_l = Fav.objects.all().filter(user=usr)
                print('fav_l : ',fav_l)
                fav_list = [fav.thing.id for fav in fav_l]
               
                # by referencing many to many field in Thing, below commented code can also be used for access user favourites
                # l=request.user.favourite_things.values('id') 
                
            except:
                print('Entered catch block in ThingListView get()')
                fav_list=None
        print('fav_list:',fav_list)
        ctx={
            'thing_list': thing_list,
            'favourites': fav_list
        }
        return render(request,self.template_name,ctx)

class ThingCreateView(OwnerCreateView):
    model=Thing
    fields = ['title','text']
    success_url = reverse_lazy('fav:index')

class ThingUpdateView(OwnerUpdateView):
    model=Thing
    fields = ['title','text']
    success_url = reverse_lazy('fav:index')

class ThingDeleteView(OwnerDeleteView):
    model = Thing
    success_url = reverse_lazy('fav:index')

class AddFavourite(LoginRequiredMixin, View):
    def post(self,request,pk):
        print(pk)
        print(request.user)
        thing_obj = get_object_or_404(Thing,pk=pk)
        fav_obj = Fav(thing=thing_obj,user=request.user)
        print(fav_obj)
        try:
            fav_obj.save() # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

class UnFavourite(LoginRequiredMixin, View):
    def post(self,request,pk):
        print(pk)
        print(request.user)    
        fav_obj = get_object_or_404(Fav,thing = pk,user=request.user)
        fav_obj.delete()
        print('unfavourited :',fav_obj)
        return HttpResponse()

favourite/templates/favourite/index.html
{% extends 'home/base_menu1.html' %}


{% block content %}
{% if thing_list %}
  <ul>
    {% for thing in thing_list %}
      <div class="row mt-2">
      
        <div class="col-12 col-sm-7">
          <li>
                <a href="">{{ thing.title }}</a>
                {% if thing.owner_id == user.id %}
                (<a href="{% url 'fav:thing_update' thing.id %}">Edit</a> |
                <a href="{% url 'fav:thing_delete' thing.id %}">Delete</a>)
                {% endif %} 
        </div>
        <div class="col-12 col-sm-3">
          {% if user.is_authenticated %}
            
            {% if thing.id in favourites %}
            <span class="fa-stack fav_test">
              <i class="fa fa-heart-o fa-stack-1x" id='unfavourite_btn_{{thing.id}}'  style="display:none" aria-hidden="true"></i> 
              <i  class="fa fa-heart fa-stack-1x" id='favourite_btn_{{thing.id}}' style="color:red" aria-hidden="true"></i>
              <input type="hidden" name='thing_id' value = {{thing.id}}>
            </span> 
            {% endif %}
            {% if thing.id not in favourites %}
            <span  class="fa-stack fav_test ">
              <i class="fa fa-heart-o fa-stack-1x" id='unfavourite_btn_{{thing.id}}' aria-hidden="true"></i>
              <i class="fa fa-heart fa-stack-1x"  id='favourite_btn_{{thing.id}}' style="display:none;color:red" aria-hidden="true"></i>
              <input type="hidden" name='thing_id'  value = {{thing.id}}>
            </span> 
            {% endif %}
              
            
          {% endif %}
        </li> 
        </div>
    </div>
    {% endfor %} 
    
  </ul>
      
      {{favourites}}
        <br>
        <a href="{% url 'fav:thing_create' %}">Create Thing</a>|
        <a href="{% url 'logout' %}?next={% url 'fav:index' %}">Logout</a>
    {% endif %}

<script type="text/javascript">
  console.log('script');
  function Favourite(fav_icon,unfav_icon,thing_id){
    $.post(
        "{% url 'fav:add_favourite' pk=123 %}".replace(/123/,thing_id),
        {'csrfmiddlewaretoken' : '{{ csrf_token }}'},
        function(data,status){
          console.log('favourited:',status);
          if(status=='success'){
            fav_icon.style.display = 'inline';
            unfav_icon.style.display ='none';
          }
        }
      );
  }

  function UnFavourite(fav_icon,unfav_icon, thing_id){
    $.post(
      '{% url 'fav:unfavourite' pk=123 %}'.replace(/123/,thing_id),
      {'csrfmiddlewaretoken' : '{{ csrf_token }}'},
      function(data,status){
          console.log('unfavourited :', status);
          fav_icon.style.display = 'none';
          unfav_icon.style.display ='inline';
      }
    );
  }
  $(document).ready(function(){
      console.log('ready')
      $('.fav_test').click(function(){
      // use below ajaxSetup way or pass cdrf_token inside post
      // $.ajaxSetup({
      //   headers: { "X-CSRFToken": '{{csrf_token}}' }
      // });
      
      // reference: https://stackoverflow.com/a/2908430
      let thing_id =$(this).children("input")[0].value;             // access thing_id from hidden html input element
      let icon_elements = $(this).children("i");                    // access fa-icons
      let unfav_icon = icon_elements[0];                            // favourite icon
      let fav_icon = icon_elements[1];                              // unfavourite icon
      // console.log(typeof(fav_elmnt));
      console.log('unfav_el',unfav_icon,'fav_el',fav_icon);
      // $(this).children("input")[0].value)
      if (fav_icon.style.display == 'none'){
          Favourite(fav_icon, unfav_icon, thing_id);
      }
      else if (unfav_icon.style.display == 'none'){
          UnFavourite(fav_icon, unfav_icon, thing_id);
      }
    });
  });

</script>
{% endblock content %}
    

favourite/templates/favourite/thing_confirm_delete.html
{% extends "home/base_menu.html" %}
{% block content %}
<h1>Delete Thing</h1>

<p>Are you sure you want to delete the thing: {{ thing }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'fav:index' %}';return false;">
</form>
{% endblock %}

favourite/templates/favourite/thing_form.html
{% extends 'home/base_menu.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Submit">
        <Button onclick="window.location='{% url 'fav:index' %}';return false;">Cancel</Button>
    </form>
{% endblock content %}
    